---
title: "Exercise-4"
author: "JeehyunOh"
date: '2021 4 23 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# 01번 문제

1부터 100까지의 수 중에서 3의 배수이면서 4의 배수는 아니 수의 합을 구하라.
```{r}
sum <- 0
for(i in 1:100){
    if(i %% 3 == 0 & i %% 4 != 0){
        sum <- sum + i
    }
}
sum
```

# 02번 문제

x와 n을 입력하면 1부터 n까지의 수 중에서 x의 배수 합을 구해주는 사용자의 정의 함수를 만들어라.
```{r}
add <- function(x,n){
    sum <- 0
    for(i in 1:n){
        if(i %% x == 0){
            sum <- sum + i
        }
    }
    return(sum)
}
# ex)
add(3,10)
```

# 03번 문제

install.packages("hflights")와 library(hflights)  명령어를 이용하여 hflights 데이터를 활용할 수 있게 하자. hflights 데이터에는 총 몇개의 NA가 존재하는가?
```{r}
library(hflights)
sum(is.na(hflights))
```

# 04번 문제

hflights 데이터에서 비행시간이 가장 긴 데이터는 몇 시간 몇 분인가?
```{r}
print(paste0(max(na.omit(hflights$AirTime))%/% 60 , "시간" ,max(na.omit(hflights$AirTime))%% 60, "분"))
```

# 05번 문제

hflights 데이터에서 비행거리가 가장 긴 데이터는 몇 마일인가?
```{r}
print(paste(max(hflights$Distance), "miles"))
```

# 06번 문제

hflights 데이터에서 비행편이 취소된 건수는 몇 건인가?
```{r}
print(paste(sum(hflights$Cancelled), "건"))
```

