---
title: "Exercise"
author: "JeehyunOh"
date: '2021 5 10 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 01번 문제

```{r}
library(rvest)
library(stringr)
library(dplyr)
library(httr)
url <- c()
base_url <- 'https://www.hanbit.co.kr/media/books'
middle_url <- '/new_book_list.html?page='
sub_url <- '&cate_cd=&srt=&searchKey=&keyWord='
new_books <- data.frame()
for(i in 1:25){
  if(i == 12) next
  url[i] <- paste0(base_url,middle_url,i,sub_url)
  html <- read_html(url[i])
  
  container <- html_node(html, '#container') # id="container"
  book_list <- html_node(container, '.new_book_list_wrap')
  sub_book_list <- html_node(book_list, '.sub_book_list_area')
  lis <- html_nodes(sub_book_list, 'li')    # <li> 모두 찾기

  title_vector <- c()
  writer_vector <- c()
  page_vector <- c()
  price_vector <- c()

  for (li in lis){
    info <- html_node(li, '.info')
    title <- info %>% 
      html_node('.book_tit') %>% 
      html_text()
    writer <- info %>% 
      html_node('.book_writer') %>% 
      html_text()
    href <- li %>% 
      html_node('.info') %>% 
      html_node('a') %>% 
      html_attr('href')
    book_url <- paste(base_url,href, sep='/')
    book_html <- read_html(book_url)
    info_list <- html_node(book_html, 'ul.info_list')
    book_lis <- html_nodes(info_list,'li')
    
    for (book_li in book_lis){
      item <- book_li %>% 
        html_node('strong') %>% 
        html_text()
      if(substring(item,1,3) == '페이지'){
        page <- book_li %>% 
          html_node('span') %>% 
          html_text()
        len <- str_length(page)
        page <- as.integer(substring(page,1,len-2))
        break
      }
    }
    pay_info <- html_node(book_html, '.payment_box.curr')
    ps <- html_nodes(pay_info, 'p')
    price <- ps[2] %>% 
      html_node('.pbr') %>% 
      html_node('strong') %>% 
      html_text()
    price <- as.integer(gsub(',','',price))
    
    title_vector <- c(title_vector, title)
    writer_vector <- c(writer_vector, writer)
    page_vector <- c(page_vector,page)
    price_vector <- c(price_vector,price)
  }
    now_books <- data.frame(
    title = title_vector,
    writer = writer_vector,
    page = page_vector,
    price = price_vector)

    new_books <- rbind(new_books,now_books)
}

View(new_books)

```

# 0.2번 문제

```{r}

url <- 'https://www.melon.com/chart/week/index.htm'
ua <- 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36'
res <- GET(url=url, user_agent(agent=ua))
html <- read_html(res)

table <- html %>% 
  html_node('.service_list_song') %>% 
  html_node('table')
trs <- table %>% 
  html_node('tbody') %>% 
  html_nodes('tr')

tr <- trs[1]
rank <- tr %>% 
  html_node('span.rank') %>% 
  html_text()
rank <- as.integer(rank)

for(i in 1:100){
  tr <- trs[i]
  tds <- html_nodes(tr,'td')
  spans <- html_nodes(tds[3],'span')
  last_str <- html_text(spans[3])
  if(length(spans)==4){
    t <- as.integer(html_text(spans[4]))
    if(last_str == '순위 동일'){
      last_rank <- rank
    }
    else if (last_str == '단계 상승'){
      last_rank <- rank + t
    } else {
      last_rank <- rank - t
    }
  } else {
    last_rank <- 999
  }
}


# anchors <- tr %>% 
#   html_node('.wrap_song_info') %>% 
#   html_nodes('a')
# html_text(anchors[1])
# html_text(anchors[2])
# 
# title <- tr %>% 
#   html_node('.ellipsis.rank01') %>% 
#   html_node('a') %>% 
#   html_text()
# artist <- tr %>% 
#   html_node('.ellipsis.rank02') %>% 
#   html_node('a') %>% 
#   html_text()
# album <- tr %>% 
#   html_node('.ellipsis.rank03') %>% 
#   html_node('a') %>% 
#   html_text()

rank_vec <- c()
last_vec <- c()
title_vec <- c()
artist_vec <- c()
album_vec <- c()
for (tr in trs){
  rank <- tr %>% 
    html_node('span.rank') %>% 
    html_text()
  rank <- as.integer(rank)
  tds <- html_nodes(tr,'td')
  spans <- html_nodes(tds[3],'span')
  last_str <- html_text(spans[3])
  if(length(spans)==4){
    t <- as.integer(html_text(spans[4]))
    if(last_str == '순위 동일'){
      last_rank <- rank
    }
    else if (last_str == '단계 상승'){
      last_rank <- rank + t
    } else {
      last_rank <- rank - t
    }
  } else {
    last_rank <- 999
  }
  title <- tr %>% 
    html_node('.ellipsis.rank01') %>% 
    html_node('a') %>% 
    html_text()
  artist <- tr %>% 
    html_node('.ellipsis.rank02') %>% 
    html_node('a') %>% 
    html_text()
  album <- tr %>% 
    html_node('.ellipsis.rank03') %>% 
    html_node('a') %>% 
    html_text()
  
  rank_vec <- c(rank_vec, rank)
  last_vec <- c(last_vec, last_rank)
  title_vec <- c(title_vec, title)
  artist_vec <- c(artist_vec, artist)
  album_vec <- c(album_vec, album)
}

week_chart <- data.frame(
  rank=rank_vec, last_rank=last_vec, title=title_vec,
  artist = artist_vec, album=album_vec
) 
View(week_chart)

```

